sonar.projectKey=crisisview-api
sonar.projectName=CrisisView API
sonar.projectVersion=1.0
sonar.host.url=http://sonarqube:9000
sonar.sources=.
sonar.exclusions=node_modules/**,__tests__/**,coverage/**
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
